### ISSUE TITLE
Gnome extension

### ISSUE THREAD

**Issue by OwenD30** [winapps-org/WinApps-Launcher#7]
Could this project be released as a Gnome extension for simplified install and updates?

**Comment by KernelGhost** [comment]
@OwenD30 Unfortunately, I'm not experienced with writing GNOME extensions. Do you know if packaging the scripts will be straightforward, or if it will require a significant rewrite? One of the main goals of this project was to keep it DE-agnostic, so if a major rewrite that breaks compatibility with other DEs is needed, it might be better to handle this as a fork rather than a modification to the project.

**Comment by oskardotglobal** [comment]
I'm pretty sure all Gnome Extension are written in JavaScript, so that's probably not happening.
